# Ativa o perfil 'test' para carregar configurações específicas do ambiente de teste
spring.profiles.active=test

# Desabilita o padrão Open Session In View para evitar problemas de lazy loading fora de transações
spring.jpa.open-in-view=false